import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const lessons = [
  { id: 1, title: "Lesson 1: Identitas & Topik", core: "～は～です / ではありません / ～か / も / の", concept: "Mengenalkan subjek, profesi, umur, kebangsaan. Penggunaan partikel dasar.", formula: "N1 は N2 です", examples: [{ jp: "わたしはマイク・ミラーです。", rom: "Watashi wa Maiku Mirā desu.", id: "Saya adalah Mike Miller." }, { jp: "サントスさんは学生じゃありません。", rom: "Santosu-san wa gakusei ja arimasen.", id: "Bapak Santos bukan pelajar." }] },
  { id: 2, title: "Lesson 2: Kata Tunjuk Benda", core: "これ / それ / あれ / この / その / あの / そうです", concept: "Menunjuk benda mati berdasarkan jarak antara pembicara dan pendengar.", formula: "これ/それ/あれ は N です", examples: [{ jp: "これは辞書です。", rom: "Kore wa jisho desu.", id: "Ini adalah kamus." }, { jp: "その傘はわたしのです。", rom: "Sono kasa wa watashi no desu.", id: "Payung itu milik saya." }] },
  { id: 3, title: "Lesson 3: Kata Tunjuk Tempat", core: "ここ / そこ / あそこ / どこ / こちら", concept: "Menunjuk tempat, lokasi ruangan, keberadaan seseorang, dan menanyakan harga.", formula: "N は ここ/そこ/あそこ/どこ です(か)", examples: [{ jp: "お手洗いはあそこです。", rom: "Otearai wa asoko desu.", id: "Toilet ada di sana." }, { jp: "この時計はいくらですか。", rom: "Kono tokei wa ikura desu ka.", id: "Jam tangan ini berapa harganya?" }] },
  { id: 4, title: "Lesson 4: Waktu & Rutinitas", core: "今～時～分 / V-ます / ～から～まで", concept: "Menyatakan waktu (jam/hari), jam operasional, dan aktivitas rutin sehari-hari.", formula: "N(waktu) に V-ます", examples: [{ jp: "今４時５分です。", rom: "Ima yoji gofun desu.", id: "Sekarang jam 4 lewat 5 menit." }, { jp: "わたしは毎朝６時に起きます。", rom: "Watashi wa maiasa rokuji ni okimasu.", id: "Saya setiap pagi bangun jam 6." }] },
  { id: 5, title: "Lesson 5: Mobilitas & Arah", core: "～へ行きます / ～で来ます / ～と帰ります", concept: "Membicarakan perpindahan tempat, moda transportasi, dan teman perjalanan.", formula: "N(tempat) へ 行きます/来ます/帰ります", examples: [{ jp: "わたしは京都へ行きます。", rom: "Watashi wa Kyouto e ikimasu.", id: "Saya pergi ke Kyoto." }, { jp: "タクシーでうちへ帰ります。", rom: "Takushii de uchi e kaerimasu.", id: "Saya pulang ke rumah naik taksi." }] },
  { id: 6, title: "Lesson 6: Tindakan & Objek", core: "～をV / ～でV / ～ませんか / ～ましょう", concept: "Menjelaskan apa yang dilakukan, di mana dilakukannya, dan mengajak seseorang.", formula: "N を V-ます", examples: [{ jp: "わたしはジュースを飲みます。", rom: "Watashi wa juusu o nomimasu.", id: "Saya minum jus." }, { jp: "いっしょに京都へ行きませんか。", rom: "Issho ni Kyouto e ikimasen ka.", id: "Maukah pergi ke Kyoto bersama-sama?" }] },
  { id: 7, title: "Lesson 7: Alat & Pemberian", core: "～でV / あげます / もらいます / もうV-ました", concept: "Menjelaskan alat/bahasa yang digunakan, transaksi memberi/menerima, dan aksi yang sudah selesai.", formula: "N(alat) で V-ます", examples: [{ jp: "箸でご飯を食べます。", rom: "Hashi de gohan o tabemasu.", id: "Makan nasi dengan sumpit." }, { jp: "木村さんに花をあげました。", rom: "Kimura-san ni hana o agemashita.", id: "Saya memberi bunga kepada Ibu Kimura." }] },
  { id: 8, title: "Lesson 8: Deskripsi Karakteristik", core: "な-adj / い-adj / ～はどうですか / どんな～", concept: "Menjelaskan sifat, bentuk, atau keadaan benda/orang menggunakan kata sifat positif & negatif.", formula: "N は na-adj/i-adj です", examples: [{ jp: "東京はにぎやかです。", rom: "Toukyou wa nigiyaka desu.", id: "Tokyo itu ramai." }, { jp: "日本のカメラは高いですが、いいです。", rom: "Nihon no kamera wa takai desu ga, ii desu.", id: "Kamera Jepang mahal, tapi bagus." }] },
  { id: 9, title: "Lesson 9: Preferensi & Kapabilitas", core: "～が好き/嫌い/上手/下手 / ～がわかります/あります", concept: "Menyatakan kesukaan, kebencian, kemahiran, kepemilikan abstrak, dan alasan (kara).", formula: "N が 好き/わかります/あります", examples: [{ jp: "わたしはイタリア料理が好きです。", rom: "Watashi wa Itaria ryouri ga suki desu.", id: "Saya suka masakan Italia." }, { jp: "時間がありませんから、新聞を読みません。", rom: "Jikan ga arimasen kara, shinbun o yomimasen.", id: "Karena tidak ada waktu, saya tidak baca koran." }] },
  { id: 10, title: "Lesson 10: Eksistensi & Posisi", core: "～に～があります/います / 位置詞 (Posisi)", concept: "Mendeskripsikan letak eksistensi benda mati (arimasu) dan makhluk hidup (imasu).", formula: "N(tempat) に N(benda) が あります/います", examples: [{ jp: "あそこにコンビニがあります。", rom: "Asoko ni konbini ga arimasu.", id: "Di sana ada minimarket." }, { jp: "ベッドの下に箱があります。", rom: "Beddo no shita ni hako ga arimasu.", id: "Di bawah kasur ada kotak." }] },
  { id: 11, title: "Lesson 11: Kuantitas & Durasi", core: "Jumlah (Counters) / 期間 (Durasi) / ～回", concept: "Menghitung benda menggunakan kata bantu bilangan spesifik dan menyatakan durasi waktu.", formula: "N を [Jumlah] V-ます", examples: [{ jp: "りんごを４つ買いました。", rom: "Ringo o yottsu kaimashita.", id: "Saya membeli 4 buah apel." }, { jp: "１週間に２回テニスをします。", rom: "Isshuukan ni nikai tenisu o shimasu.", id: "Bermain tenis dua kali dalam satu minggu." }] },
  { id: 12, title: "Lesson 12: Masa Lalu & Komparasi", core: "Tense Kata Sifat / ～より / ～のほうが / ～で一番", concept: "Merubah kata sifat ke bentuk lampau dan membandingkan dua hal atau lebih.", formula: "N1 は N2 より Adj です", examples: [{ jp: "昨日は雨でした。", rom: "Kinou wa ame deshita.", id: "Kemarin hujan." }, { jp: "北海道は九州より大きいです。", rom: "Hokkaidou wa Kyuushuu yori ookii desu.", id: "Hokkaido lebih besar daripada Kyushu." }] },
  { id: 13, title: "Lesson 13: Keinginan & Tujuan", core: "～が欲しい / ～たい / ～へ～に行きます", concept: "Mengekspresikan keinginan memiliki (hoshii), ingin melakukan (tai), dan tujuan kepergian.", formula: "V-ます(coret ます) + たいです", examples: [{ jp: "わたしはパソコンが欲しいです。", rom: "Watashi wa pasokon ga hoshii desu.", id: "Saya ingin komputer." }, { jp: "フランスへ料理を習いに行きます。", rom: "Furansu e ryouri o narai ni ikimasu.", id: "Pergi ke Prancis untuk belajar memasak." }] },
  { id: 14, title: "Lesson 14: Permintaan & Progresif", core: "V-て / ～てください / ～ています / ～ましょうか", concept: "Pengenalan bentuk Te. Digunakan untuk meminta sesuatu, aksi yang sedang terjadi, dan menawarkan bantuan.", formula: "V-て + ください / います", examples: [{ jp: "ちょっと待ってください。", rom: "Chotto matte kudasai.", id: "Tolong tunggu sebentar." }, { jp: "ミラーさんは今電話をかけています。", rom: "Miraa-san wa ima denwa o kakete imasu.", id: "Sdr. Miller sekarang sedang menelepon." }] },
  { id: 15, title: "Lesson 15: Izin, Larangan & Status", core: "～てもいいです / ～てはいけません / ～ています", concept: "Meminta/memberi izin, melarang dengan tegas, serta aksi berkelanjutan (status/pekerjaan).", formula: "V-て + もいいですか / はいけません", examples: [{ jp: "ここで写真を撮ってもいいですか。", rom: "Koko de shashin o totte mo ii desu ka.", id: "Boleh memotret di sini?" }, { jp: "ここに車を止めてはいけません。", rom: "Koko ni kuruma o tomete wa ikemasen.", id: "Tidak boleh parkir mobil di sini." }] },
  { id: 16, title: "Lesson 16: Urutan & Koneksi", core: "V-て、V-て、～ / V-てから / Adj-て / N-で", concept: "Menggabungkan beberapa kalimat (kata kerja, kata sifat, atau kata benda) menjadi satu rangkaian.", formula: "V1-て、V2-て、V3-ます", examples: [{ jp: "朝ジョギングをして、シャワーを浴びて、会社へ行きます。", rom: "Asa jogingu o shite, shawaa o abite, kaisha e ikimasu.", id: "Pagi hari jogging, mandi, lalu pergi ke kantor." }, { jp: "コンサートが終わってから、レストランで食事しました。", rom: "Konsato ga owatte kara, resutoran de shokuji shimashita.", id: "Setelah konser selesai, makan di restoran." }] },
  { id: 17, title: "Lesson 17: Kewajiban & Negasi", core: "V-ない / ～ないでください / ～なければなりません", concept: "Bentuk negatif kasual (Nai). Meminta agar jangan melakukan sesuatu dan menyatakan kewajiban (harus).", formula: "V-ない + でください / ければなりません", examples: [{ jp: "ここで写真を撮らないでください。", rom: "Koko de shashin o toranaide kudasai.", id: "Tolong jangan memotret di sini." }, { jp: "毎日薬を飲まなければなりません。", rom: "Mainichi kusuri o nomanakereba narimasen.", id: "Setiap hari harus minum obat." }] },
  { id: 18, title: "Lesson 18: Kemampuan & Waktu Sebelum", core: "V-る (Kamus) / ～ことができます / 趣味は～ / ～前に", concept: "Bentuk Kamus. Digunakan untuk kebisaan, hobi, dan urutan waktu 'sebelum'.", formula: "V-る + ことができます / 前に", examples: [{ jp: "ミラーさんは漢字を読むことができます。", rom: "Miraa-san wa kanji o yomu koto ga dekimasu.", id: "Sdr. Miller bisa membaca kanji." }, { jp: "寝る前に、本を読みます。", rom: "Neru mae ni, hon o yomimasu.", id: "Sebelum tidur, membaca buku." }] },
  { id: 19, title: "Lesson 19: Pengalaman & Daftar Aksi", core: "V-た / ～たことがあります / ～たり、～たり / ～なります", concept: "Bentuk lampau (Ta). Mengutarakan pengalaman masa lalu, menyebutkan aktivitas acak, dan perubahan (menjadi).", formula: "V-た + ことがあります / りします", examples: [{ jp: "馬に乗ったことがあります。", rom: "Uma ni notta koto ga arimasu.", id: "Pernah naik kuda." }, { jp: "日曜日はテニスをしたり、映画を見たりします。", rom: "Nichiyoubi wa tenisu o shitari, eiga o mitari shimasu.", id: "Hari minggu bermain tenis, menonton film, dll." }] },
  { id: 20, title: "Lesson 20: Bentuk Biasa (Futsuukei)", core: "丁寧体 (Sopan) vs 普通体 (Biasa/Kasual)", concept: "Menyederhanakan kalimat masu/desu menjadi bentuk kasual (kamus/nai/ta/nakatta) untuk teman dan keluarga.", formula: "V/Adj/N dalam bentuk Futsuukei", examples: [{ jp: "明日東京へ行く？ うん、行く。", rom: "Ashita Toukyou e iku? Un, iku.", id: "Besok pergi ke Tokyo? Ya, pergi." }, { jp: "そのカレー、おいしい？ ううん、辛い。", rom: "Sono karee, oishii? Uun, karai.", id: "Kari itu enak? Nggak, pedas." }] },
  { id: 21, title: "Lesson 21: Opini & Dugaan", core: "～と思います / ～と言いました / ～でしょう？", concept: "Menyampaikan pemikiran pribadi, mengutip perkataan orang lain, dan meminta persetujuan pendengar.", formula: "Futsuukei + と思います / と言いました", examples: [{ jp: "明日は雨が降ると思います。", rom: "Ashita wa ame ga furu to omoimasu.", id: "Menurut saya besok hujan." }, { jp: "首相は来月アメリカへ行くと言いました。", rom: "Shushou wa raigetsu Amerika e iku to iimashita.", id: "Perdana Menteri berkata akan pergi ke Amerika bulan depan." }] },
  { id: 22, title: "Lesson 22: Anak Kalimat (Modifikasi Noun)", core: "V-Futsuukei + N / Adj/N + N", concept: "Kalimat lengkap digunakan sebagai 'kata sifat' untuk menjelaskan sebuah kata benda (Noun Clause).", formula: "[Kalimat Penjelas Futsuukei] + N", examples: [{ jp: "これはミラーさんが作ったケーキです。", rom: "Kore wa Miraa-san ga tsukutta keeki desu.", id: "Ini adalah kue yang dibuat oleh Sdr. Miller." }, { jp: "わたしはカリナさんが描いた絵が好きです。", rom: "Watashi wa Karina-san ga kaita e ga suki desu.", id: "Saya suka lukisan yang digambar Karina." }] },
  { id: 23, title: "Lesson 23: Saat & Kondisional Mutlak", core: "～とき / ～と / ～をV (Gerak)", concept: "Menyatakan 'ketika/saat' suatu kejadian, dan 'kalau' yang sifatnya pasti/alami (sebab-akibat mesin/alam).", formula: "Futsuukei + とき / V-る + と", examples: [{ jp: "図書館で本を借りるとき、カードが要ります。", rom: "Toshokan de hon o kariru toki, kaado ga irimasu.", id: "Saat meminjam buku di perpustakaan, butuh kartu." }, { jp: "このボタンを押すと、おつりが出ます。", rom: "Kono botan o osu to, otsuri ga demasu.", id: "Kalau pencet tombol ini, kembaliannya keluar." }] },
  { id: 24, title: "Lesson 24: Aksi Kebaikan/Bantuan", core: "～てくれます / ～てもらいます / ～てあげます", concept: "Menyatakan siapa yang memberi bantuan/aksi kepada siapa. Kuremasu khusus untuk bantuan ke diri saya.", formula: "V-て + もらいます/くれます/あげます", examples: [{ jp: "佐藤さんがわたしに傘を貸してくれました。", rom: "Satou-san ga watashi ni kasa o kashite kuremashita.", id: "Sdr. Sato meminjamkan saya payung." }, { jp: "わたしは山田さんに病院へ連れて行ってもらいました。", rom: "Watashi wa Yamada-san ni byouin e tsurete itte moraimashita.", id: "Saya diantar ke rumah sakit oleh Sdr. Yamada." }] },
  { id: 25, title: "Lesson 25: Pengandaian & Kontradiksi", core: "～たら / ～ても", concept: "Kondisional paling fleksibel: 'Jika/kalau' dan 'Bahkan jika / walaupun'.", formula: "V-た + ら / V-て + も", examples: [{ jp: "雨が降ったら、行きません。", rom: "Ame ga futtara, ikimasen.", id: "Kalau hujan, saya tidak pergi." }, { jp: "いくら考えても、わかりません。", rom: "Ikura kangaetemo, wakarimasen.", id: "Sebanyak apa pun saya berpikir, saya tidak mengerti." }] },
  // Phase 2 (Lessons 26-50)
  { id: 26, title: "Lesson 26: Penjelasan & Klarifikasi", core: "～んです / ～んですが、～ていただけませんか", concept: "Bentuk eksplanatori untuk meminta penjelasan, memberi alasan, atau membuka topik permintaan tolong.", formula: "Futsuukei + んです", examples: [{ jp: "どうして遅れたんですか。", rom: "Doushite okureta n desu ka.", id: "Kenapa Anda terlambat? (meminta penjelasan)" }, { jp: "日本語を書いたんですが、ちょっと見ていただけませんか。", rom: "Nihongo o kaita n desu ga, chotto mite itadakemasen ka.", id: "Saya menulis bahasa Jepang, maukah tolong periksakan?" }] },
  { id: 27, title: "Lesson 27: Kesanggupan & Persepsi", core: "可能形 (Potential) / 見えます / 聞こえます", concept: "Kata kerja bentuk potensial (bisa/mampu). Juga membedakan 'terlihat/terdengar' secara alami.", formula: "V-potential", examples: [{ jp: "わたしは漢字が読めます。", rom: "Watashi wa kanji ga yomemasu.", id: "Saya bisa membaca kanji." }, { jp: "ここから山が見えます。", rom: "Koko kara yama ga miemasu.", id: "Dari sini terlihat gunung (secara alami)." }] },
  { id: 28, title: "Lesson 28: Aksi Paralel & Repetisi", core: "～ながら / ～ています / ～し、～し", concept: "Melakukan dua hal bersamaan, rutinitas, dan menjabarkan banyak alasan (dan juga... dan juga).", formula: "V-ます(coret) + ながら / Futsuukei + し", examples: [{ jp: "音楽を聞きながら食事します。", rom: "Ongaku o kikinagara shokuji shimasu.", id: "Makan sambil mendengarkan musik." }, { jp: "彼は熱心だし、まじめだし、経験もあります。", rom: "Kare wa nesshin da shi, majime da shi, keiken mo arimasu.", id: "Dia antusias, serius, dan punya pengalaman." }] },
  { id: 29, title: "Lesson 29: Keadaan Intransitif & Penyesalan", core: "自動詞 (Intransitive) + ています / ～てしまいました", concept: "Mendeskripsikan status/keadaan benda tanpa menyebut pelakunya. Serta penyesalan/penyelesaian total.", formula: "V-intransitive-て + います / しまいました", examples: [{ jp: "窓が閉まっています。", rom: "Mado ga shimatte imasu.", id: "Jendelanya tertutup (keadaan)." }, { jp: "パスポートをなくしてしまいました。", rom: "Pasupooto o nakushite shimaimashita.", id: "Saya tak sengaja menghilangkan paspor (penyesalan)." }] },
  { id: 30, title: "Lesson 30: Kondisi Sengaja & Persiapan", core: "他動詞 (Transitive) + てあります / ～ておきます", concept: "Mendeskripsikan keadaan akibat tindakan sengaja seseorang, dan melakukan aksi sebagai persiapan masa depan.", formula: "V-transitive-て + あります / おきます", examples: [{ jp: "カレンダーがかけてあります。", rom: "Karendaa ga kakete arimasu.", id: "Kalender digantungkan (sengaja oleh seseorang)." }, { jp: "旅行の前に、ホテルを予約しておきます。", rom: "Ryokou no mae ni, hoteru o yoyaku shite okimasu.", id: "Sebelum perjalanan, saya memesan hotel (persiapan)." }] },
  { id: 31, title: "Lesson 31: Niat & Keputusan Sementara", core: "意向形 (Volitional) / ～と思っています / ～つもりです", concept: "Menyatakan niat dan rencana. Volitional adalah bentuk kasual dari ~mashou.", formula: "V-volitional + と思っています", examples: [{ jp: "週末は海へ行こうと思っています。", rom: "Shuumatsu wa umi e ikou to omotte imasu.", id: "Akhir pekan saya berencana pergi ke laut." }, { jp: "車を買わないつもりです。", rom: "Kuruma o kawanai tsumori desu.", id: "Saya berniat tidak membeli mobil." }] },
  { id: 32, title: "Lesson 32: Nasihat & Kemungkinan", core: "～ほうがいいです / ～でしょう / ～かもしれません", concept: "Memberikan nasihat kuat, memprediksi hal dengan yakin (deshou), dan kemungkinan kecil (kamoshiremasen).", formula: "V-た/ない + ほうがいいです", examples: [{ jp: "毎日運動したほうがいいです。", rom: "Mainichi undou shita hou ga ii desu.", id: "Sebaiknya berolahraga setiap hari." }, { jp: "午後は雨が降るかもしれません。", rom: "Gogo wa ame ga furu kamoshiremasen.", id: "Sore ini mungkin saja turun hujan." }] },
  { id: 33, title: "Lesson 33: Perintah, Larangan & Makna", core: "命令形 (Imperative) / 禁止形 (Prohibitive) / ～という意味です", concept: "Bentuk perintah kasar dan larangan keras. Digunakan pada rambu, darurat, dan menjelaskan arti kata.", formula: "V-imperative / V-る+な", examples: [{ jp: "早く走れ！", rom: "Hayaku hashire!", id: "Cepat lari!" }, { jp: "「立入禁止」は入るなという意味です。", rom: "Tachiiri-kinshi wa hairu na to iu imi desu.", id: "'Dilarang Masuk' artinya jangan masuk." }] },
  { id: 34, title: "Lesson 34: Sesuai Dengan & Urutan Aksi", core: "～とおりに / ～たあとで / ～て/ないで", concept: "Melakukan persis seperti contoh, setelah kejadian X maka Y, dan melakukan X dengan/tanpa Y.", formula: "V-る/V-た + とおりに", examples: [{ jp: "わたしが言うとおりに、書いてください。", rom: "Watashi ga iu toori ni, kaite kudasai.", id: "Tolong tulis sesuai dengan apa yang saya ucapkan." }, { jp: "仕事が終わったあとで、飲みに行きませんか。", rom: "Shigoto ga owatta ato de, nomi ni ikimasen ka.", id: "Setelah pekerjaan selesai, maukah pergi minum?" }] },
  { id: 35, title: "Lesson 35: Kondisional (Syarat Mutlak)", core: "条件形 (Conditional ～ば) / ～なら", concept: "Bentuk syarat (jika). Digunakan untuk memberikan syarat mutlak. Nara untuk merespons topik spesifik.", formula: "V-eba (ば) / N+なら", examples: [{ jp: "天気がよければ、行きます。", rom: "Tenki ga yokereba, ikimasu.", id: "Jika cuacanya bagus, saya akan pergi." }, { jp: "温泉なら、白馬がいいですよ。", rom: "Onsen nara, Hakuba ga ii desu yo.", id: "Kalau (bicara soal) onsen, Hakuba sangat bagus lho." }] },
  { id: 36, title: "Lesson 36: Usaha & Perubahan Kemampuan", core: "～ように (Tujuan) / ～ようになります / ～ようにします", concept: "Menyatakan tujuan, perubahan kemampuan dari tidak bisa menjadi bisa, dan kebiasaan rutin.", formula: "V-る/ない + ように", examples: [{ jp: "早く泳げるように、毎日練習しています。", rom: "Hayaku oyogeru you ni, mainichi renshuu shite imasu.", id: "Saya latihan tiap hari agar bisa berenang cepat." }, { jp: "日本語が話せるようになりました。", rom: "Nihongo ga hanaseru you ni narimashita.", id: "Saya jadi bisa (mulai bisa) bicara bahasa Jepang." }] },
  { id: 37, title: "Lesson 37: Bentuk Pasif (Korban/Penerima)", core: "受身形 (Passive - られる)", concept: "Menerangkan kejadian di mana subjek dikenai tindakan (sering kali berkonotasi negatif/dirugikan).", formula: "N1 は N2 に V-passive", examples: [{ jp: "わたしは先生に褒められました。", rom: "Watashi wa sensei ni homeraremashita.", id: "Saya dipuji oleh guru." }, { jp: "電車の中で足を踏まれました。", rom: "Densha no naka de ashi o fumaremashita.", id: "Kaki saya diinjak (oleh seseorang) di dalam kereta." }] },
  { id: 38, title: "Lesson 38: Nominalisasi (Kata Benda Buatan)", core: "V-るのは / V-るのが / V-るのを", concept: "Menambahkan Partikel NO untuk mengubah verba/kalimat menjadi kata benda agar bisa diberi sifat/objek.", formula: "V-る + の は/が/を", examples: [{ jp: "一人で星を見るのが好きです。", rom: "Hitori de hoshi o miru no ga suki desu.", id: "Saya suka melihat bintang sendirian." }, { jp: "薬を飲むのを忘れました。", rom: "Kusuri o nomu no o wasuremashita.", id: "Saya lupa meminum obat." }] },
  { id: 39, title: "Lesson 39: Alasan & Emosi", core: "～て (Alasan) / ～ので (Karena)", concept: "Menyatakan alasan yang memicu perasaan, serta penggunaan 'node' sebagai alasan objektif/sopan.", formula: "V-て、[Perasaan] / Futsuukei + ので", examples: [{ jp: "ニュースを聞いて、びっくりしました。", rom: "Nyūsu o kiite, bikkuri shimashita.", id: "Saya kaget karena mendengar berita." }, { jp: "用事があるので、お先に失礼します。", rom: "Youji ga aru node, osaki ni shitsurei shimasu.", id: "Karena ada urusan, saya permisi duluan." }] },
  { id: 40, title: "Lesson 40: Kalimat Tanya Bersarang", core: "～か / ～かどうか / ～てみます", concept: "Memasukkan anak kalimat tanya ke kalimat utama. Mencoba melakukan sesuatu (te mimasu).", formula: "Futsuukei + か / かどうか", examples: [{ jp: "会議は何時に終わるか、わかりません。", rom: "Kaigi wa nanji ni owaru ka, wakarimasen.", id: "Saya tidak tahu rapatnya selesai jam berapa." }, { jp: "本当かどうか、確かめてください。", rom: "Hontou ka dou ka, tashikamete kudasai.", id: "Tolong pastikan apakah itu benar atau tidak." }] },
  { id: 41, title: "Lesson 41: Pemberian (Hormat & Rendah Hati)", core: "いただきます / くださいます / やります", concept: "Menyatakan transaksi memberi/menerima bantuan dengan tingkatan hierarki (atasan, bawahan, hewan).", formula: "V-て + いただきます/くださいます/やります", examples: [{ jp: "部長がわたしに時計をくださいました。", rom: "Buchou ga watashi ni tokei o kudasaimashita.", id: "Kepala bagian memberi saya jam tangan (hormat)." }, { jp: "わたしは犬にえさをやりました。", rom: "Watashi wa inu ni esa o yarimashita.", id: "Saya memberi makan kepada anjing (bawah)." }] },
  { id: 42, title: "Lesson 42: Tujuan & Manfaat Mutlak", core: "～ために / ～に (Tujuan Alat)", concept: "Menyatakan demi/untuk tujuan besar (tame ni) dan fungsi suatu benda/perkakas (ni).", formula: "V-る / Nの + ために", examples: [{ jp: "自分の店を持つために、貯金しています。", rom: "Jibun no mise o motsu tame ni, chokin shite imasu.", id: "Menabung demi memiliki toko sendiri." }, { jp: "この辞書は漢字を調べるのに役に立ちます。", rom: "Kono jisho wa kanji o shiraberu noni yaku ni tachimasu.", id: "Kamus ini berguna untuk mengecek kanji." }] },
  { id: 43, title: "Lesson 43: Kesan Visual & Aksi Pulang-Pergi", core: "～そうです (Kelihatannya) / ～て来ます", concept: "Mengutarakan asumsi dari tampilan luar (sou desu) dan tindakan pergi ke suatu tempat lalu kembali.", formula: "Adj/V-ます(coret) + そうです / V-て + 来ます", examples: [{ jp: "このケーキはおいしそうです。", rom: "Kono keeki wa oishisou desu.", id: "Kue ini kelihatannya enak." }, { jp: "ちょっとスーパーへ行って来ます。", rom: "Chotto suupaa e itte kimasu.", id: "Pergi ke supermarket sebentar (lalu kembali)." }] },
  { id: 44, title: "Lesson 44: Batas Lebar & Kemudahan", core: "～すぎます / ～やすい / ～にくい / ～くします", concept: "Kondisi berlebihan (sugi), kemudahan/kesulitan, dan tindakan membuat benda menjadi sifat tertentu.", formula: "V-ます(coret) + すぎます/やすい/にくい", examples: [{ jp: "夕べお酒を飲みすぎました。", rom: "Yuube osake o nomisugimashita.", id: "Semalam saya minum terlalu banyak." }, { jp: "このパソコンは使いやすいです。", rom: "Kono pasokon wa tsukaiyasui desu.", id: "Komputer ini mudah digunakan." }] },
  { id: 45, title: "Lesson 45: Kondisi Darurat & Kontradiksi", core: "～場合は / ～のに (Padahal)", concept: "Memberi instruksi untuk situasi tertentu (baai wa) dan menyatakan kekecewaan akan hasil kontradiktif (noni).", formula: "Futsuukei + 場合は / のに", examples: [{ jp: "地震の場合は、外へ出てください。", rom: "Jishin no baai wa, soto e dete kudasai.", id: "Jika terjadi gempa, tolong keluar." }, { jp: "約束をしたのに、彼女は来ませんでした。", rom: "Yakusoku o shita noni, kanojo wa kimasen deshita.", id: "Padahal sudah berjanji, tapi dia tidak datang." }] },
  { id: 46, title: "Lesson 46: Tahap Aksi Tepat", core: "～ところです / ～ばかりです / ～はずです", concept: "Menerangkan momen tepat (baru mau/sedang/baru selesai) dan keyakinan logis objektif (hazu).", formula: "V-る/て/た + ところです", examples: [{ jp: "今からお茶を飲むところです。", rom: "Ima kara ocha o nomu tokoro desu.", id: "Baru mau minum teh sekarang." }, { jp: "彼は会議に出たはずです。", rom: "Kare wa kaigi ni deta hazu desu.", id: "Dia seharusnya tadi ikut rapat (logikanya)." }] },
  { id: 47, title: "Lesson 47: Hearsay (Katanya) & Bukti Asumsi", core: "～そうです (Katanya) / ～ようです (Tampaknya)", concept: "Melaporkan 100% informasi dari sumber lain (sou desu hearsay) dan menebak dari bukti indera (you desu).", formula: "Futsuukei + そうです / ようです", examples: [{ jp: "天気予報によると、明日は寒くなるそうです。", rom: "Tenkiyohou ni yoru to, ashita wa samuku naru sou desu.", id: "Menurut prakiraan cuaca, besok akan jadi dingin." }, { jp: "人が大勢集まっています。事故のようです。", rom: "Hito ga oozei atsumatte imasu. Jiko no you desu.", id: "Banyak orang berkumpul. Sepertinya ada kecelakaan." }] },
  { id: 48, title: "Lesson 48: Paksaan & Izin (Causative)", core: "使役形 (Causative - させる)", concept: "Menyuruh, memaksa, atau mengizinkan seseorang melakukan suatu hal.", formula: "N(orang) に V-causative", examples: [{ jp: "部長はわたしにレポートを書かせました。", rom: "Buchou wa watashi ni repooto o kakasemashita.", id: "Kepala bagian menyuruh saya menulis laporan." }, { jp: "子供を遊ばせます。", rom: "Kodomo o asobasemasu.", id: "Membiarkan anak bermain." }] },
  { id: 49, title: "Lesson 49: Bahasa Hormat (Sonkeigo)", core: "尊敬語 (Sonkeigo)", concept: "Meninggikan tindakan pihak lain yang statusnya lebih tinggi (tamu/bos/guru).", formula: "お/ご + V-ます(coret) + になります", examples: [{ jp: "社長はもうお帰りになりました。", rom: "Shachou wa mou okaeri ni narimashita.", id: "Bapak Direktur sudah pulang." }, { jp: "先生は何を召し上がりますか。", rom: "Sensei wa nani o meshiagarimasu ka.", id: "Pak guru mau makan apa? (hormat)" }] },
  { id: 50, title: "Lesson 50: Bahasa Rendah Hati (Kenjougo)", core: "謙譲語 (Kenjougo)", concept: "Merendahkan aksi diri sendiri demi meninggikan pihak lawan (sikap melayani).", formula: "お/ご + V-ます(coret) + します", examples: [{ jp: "わたしがお荷物をお持ちします。", rom: "Watashi ga onimotsu o omochishimasu.", id: "Biar saya yang bawakan barang Anda." }, { jp: "明日３時に伺います。", rom: "Ashita sanji ni ukagaimasu.", id: "Saya akan berkunjung besok jam 3." }] }
];

const fileContent = `// Auto-generated detailed Minna no Nihongo 1-50 Data\nexport const MINNA_LESSONS = ${JSON.stringify(lessons, null, 2)};\n`;
fs.writeFileSync(path.join(__dirname, '../src/data/minnaData.js'), fileContent);
console.log('Successfully enhanced minnaData.js with comprehensive, accurate grammar points.');
